version: '3'

services:
  node:
    build:
      dockerfile: ./dev-dockerfile
    restart: unless-stopped
    init: true
    depends_on:
      - db
    volumes:
      - ./server:/code
      - ./client:/client
    ports:
      - 8080:8080
    environment:
      - DBHOST=db
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db
    volumes:
      - ./mysql:/var/lib/mysql
