version: '3'

services:
  node:
    build:
      dockerfile: ./prod-dockerfile
    scale: 3
    restart: unless-stopped
    init: true
    depends_on:
      - db
    environment:
      - DBHOST=db
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db
    volumes:
      - ./mysql:/var/lib/mysql
  lb:
    image: nginx:alpine
    depends_on:
      - node
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '8080:8080'

