version: '3'

services:
  node:
    build:
      dockerfile: ./dev-dockerfile
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./server:/code
      - ./client:/client
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DBHOST=db
    #command: node /code
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db
    volumes:
      - ./mysql:/var/lib/mysql
